apiVersion: v1
kind: Service
metadata:
  name: mysql # Service 이름 -> 다른 파드에서 DB 호스트로 참조할 때 사용 (API Deployment에서 DB_HOST=mysql)
spec:
  type: ClusterIP # 클러스터 내부에서만 접근 가능 (외부 접속 불가)
  selector: # 어떤 파드를 Service가 연결할지 선택
    app: mysql
  ports:
    - port: 3306 # Service가 클러스터 내부에서 열어주는 포트
      targetPort: 3306 # 실제 파드 컨테이너가 사용하는 포트
      # 여기서는 MySQL 컨테이너가 3306 포트를 사용하므로 동일하게 설정 -> 클러스터 내부 다른 파드(API)에서 mysql:3306으로 접속 가능
